#!/bin/sh
# Synopsis
# ------------------------------------------------------------------------------
# Run hub if it is in $PATH otherwise run git
#
function hub-is-in-path {
	which hub > /dev/null 2>&1
}

if hub-is-in-path; then
	hub "$@"
else
	git "$@"
fi
